[2018-Oct-11 09:12:07][Autoplacement24in96][CRITICAL] Encountered a KeyError exception: Container(https://egclaritydev.mvm.ed.ac.uk/api/v2/containers/27-4573)
[2018-Oct-11 09:12:07][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 33, in _run
    input_container_nested_dict[input.container][input.location] = output
KeyError: Container(https://egclaritydev.mvm.ed.ac.uk/api/v2/containers/27-4573)

[2018-Oct-11 09:15:11][Autoplacement24in96][CRITICAL] Encountered a KeyError exception: '1:A'
[2018-Oct-11 09:15:11][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 62, in _run
    output_placement.append((input_container_nested_dict[key][row+":"+column],
KeyError: '1:A'

[2018-Oct-11 09:17:07][Autoplacement24in96][CRITICAL] Encountered a KeyError exception: 'A:1'
[2018-Oct-11 09:17:07][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 62, in _run
    output_placement.append((input_container_nested_dict[key][row+":"+column],
KeyError: 'A:1'

[2018-Oct-11 09:17:49][Autoplacement24in96][CRITICAL] Encountered a KeyError exception: 'A:1'
[2018-Oct-11 09:17:49][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 62, in _run
    output_placement.append((input_container_nested_dict[container][row+":"+column],
KeyError: 'A:1'

[2018-Oct-11 09:19:52][Autoplacement24in96][CRITICAL] Encountered a KeyError exception: 'E:1'
[2018-Oct-11 09:19:52][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 62, in _run
    output_placement.append((input_container_nested_dict[container][row+":"+column],
KeyError: 'E:1'

