[2018-Oct-10 17:03:19][GenerateHamiltonInputUCT][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-10 17:03:19][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 68, in _run
    adapter_well = input.reagent_labels[0].split("_")[0]
IndexError: list index out of range

[2018-Oct-10 17:03:55][GenerateHamiltonInputUCT][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-10 17:03:55][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 68, in _run
    adapter_well = input.reagent_labels[0].split("_")
IndexError: list index out of range

[2018-Oct-10 17:04:22][GenerateHamiltonInputUCT][CRITICAL] Encountered a NameError exception: name 'adapter_well' is not defined
[2018-Oct-10 17:04:22][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 72, in _run
    csv_line = [input.container.name, input_location, input.name,adapter_well]
NameError: name 'adapter_well' is not defined

[2018-Oct-10 17:04:49][GenerateHamiltonInputUCT][CRITICAL] Encountered a NameError exception: name 'adapter_well' is not defined
[2018-Oct-10 17:04:49][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 72, in _run
    csv_line = [input.container.name, input_location, input.name,adapter_well]
NameError: name 'adapter_well' is not defined

[2018-Oct-10 17:05:36][GenerateHamiltonInputUCT][CRITICAL] Encountered a AttributeError exception: 'list' object has no attribute 'reagent_labels'
[2018-Oct-10 17:05:36][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 68, in _run
    print(output.reagent_labels)
AttributeError: 'list' object has no attribute 'reagent_labels'

[2018-Oct-10 17:06:08][GenerateHamiltonInputUCT][CRITICAL] Encountered a NameError exception: name 'adapter_well' is not defined
[2018-Oct-10 17:06:08][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 72, in _run
    csv_line = [input.container.name, input_location, input.name,adapter_well]
NameError: name 'adapter_well' is not defined

[2018-Oct-10 17:06:37][GenerateHamiltonInputUCT][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-10 17:06:37][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 69, in _run
    adapter_well = input.reagent_labels[0].split("_")[0]
IndexError: list index out of range

[2018-Oct-10 17:06:44][GenerateHamiltonInputUCT][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-10 17:06:44][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 69, in _run
    adapter_well = input.reagent_labels[0].split("_")
IndexError: list index out of range

[2018-Oct-10 17:06:56][GenerateHamiltonInputUCT][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: '/mnt/EGCGgeneral/HAMILTON_INPUTS/KAPA_MAKE_LIBRARIES/KAPA_MAKE_LIBRARIES.csv'
[2018-Oct-10 17:06:56][GenerateHamiltonInputUCT][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_uct.py", line 103, in _run
    with open(self.shared_drive_path + 'KAPA_MAKE_LIBRARIES.csv', 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/EGCGgeneral/HAMILTON_INPUTS/KAPA_MAKE_LIBRARIES/KAPA_MAKE_LIBRARIES.csv'

