[2018-Nov-09 12:07:15][Autoplacement_seq_plate_quant][CRITICAL] Encountered a NameError exception: name 'input_outputs_maps' is not defined
[2018-Nov-09 12:07:15][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 37, in _run
    for input_output in input_outputs_maps:
NameError: name 'input_outputs_maps' is not defined

[2018-Nov-09 12:07:55][Autoplacement_seq_plate_quant][CRITICAL] Encountered a NameError exception: name 'uri' is not defined
[2018-Nov-09 12:07:55][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 38, in _run
    input = input_output[0][uri]
NameError: name 'uri' is not defined

[2018-Nov-09 13:46:26][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: unhashable type: 'dict'
[2018-Nov-09 13:46:26][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 42, in _run
    if not input_output_PerInput_dict[input]:
TypeError: unhashable type: 'dict'

[2018-Nov-09 13:47:51][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: unhashable type: 'dict'
[2018-Nov-09 13:47:51][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 42, in _run
    if not input in input_output_PerInput_dict.keys():
TypeError: unhashable type: 'dict'

[2018-Nov-09 13:48:19][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: unhashable type: 'dict'
[2018-Nov-09 13:48:19][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 42, in _run
    if input in input_output_PerInput_dict.keys():
TypeError: unhashable type: 'dict'

[2018-Nov-09 13:49:42][Autoplacement_seq_plate_quant][CRITICAL] Encountered a KeyError exception: Artifact(https://egclaritydev.mvm.ed.ac.uk/api/v2/artifacts/16C-1052PA1?state=91434)
[2018-Nov-09 13:49:42][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 45, in _run
    input_output_PerInput_dict.update(input,input_output_PerInput_dict[input]+input_ouput[1]['uri'])
KeyError: Artifact(https://egclaritydev.mvm.ed.ac.uk/api/v2/artifacts/16C-1052PA1?state=91434)

[2018-Nov-09 13:50:38][Autoplacement_seq_plate_quant][CRITICAL] Encountered a KeyError exception: Artifact(https://egclaritydev.mvm.ed.ac.uk/api/v2/artifacts/16C-1052PA1?state=91434)
[2018-Nov-09 13:50:38][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 45, in _run
    input_output_PerInput_dict.update(input,input_output_PerInput_dict[input]+input_ouput[1]['uri'])
KeyError: Artifact(https://egclaritydev.mvm.ed.ac.uk/api/v2/artifacts/16C-1052PA1?state=91434)

[2018-Nov-09 13:51:01][Autoplacement_seq_plate_quant][CRITICAL] Encountered a NameError exception: name 'input_ouput' is not defined
[2018-Nov-09 13:51:01][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 45, in _run
    input_output_PerInput_dict.update(input,input_output_PerInput_dict[input]+input_ouput[1]['uri'])
NameError: name 'input_ouput' is not defined

[2018-Nov-09 13:51:12][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: unsupported operand type(s) for +: 'Artifact' and 'Artifact'
[2018-Nov-09 13:51:12][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 45, in _run
    input_output_PerInput_dict.update(input,input_output_PerInput_dict[input]+input_output[1]['uri'])
TypeError: unsupported operand type(s) for +: 'Artifact' and 'Artifact'

[2018-Nov-09 14:02:21][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: '<' not supported between instances of 'Artifact' and 'Artifact'
[2018-Nov-09 14:02:21][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 55, in _run
    outputs = input_output_PerInput_dict[input].sort()
TypeError: '<' not supported between instances of 'Artifact' and 'Artifact'

[2018-Nov-09 14:05:10][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: object of type 'NoneType' has no len()
[2018-Nov-09 14:05:10][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 56, in _run
    print(len(outputs))
TypeError: object of type 'NoneType' has no len()

[2018-Nov-09 14:05:31][Autoplacement_seq_plate_quant][CRITICAL] Encountered a TypeError exception: object of type 'NoneType' has no len()
[2018-Nov-09 14:05:31][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 57, in _run
    if len(outputs) != 3:
TypeError: object of type 'NoneType' has no len()

[2018-Nov-09 14:12:48][Autoplacement_seq_plate_quant][CRITICAL] Encountered a NameError exception: name 'x' is not defined
[2018-Nov-09 14:12:48][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 55, in _run
    outputs = sorted(input_output_PerInput_dict[input],x,x.name, reverse=False)
NameError: name 'x' is not defined

[2018-Nov-09 14:14:40][Autoplacement_seq_plate_quant][CRITICAL] Encountered a NameError exception: name 'Artifact' is not defined
[2018-Nov-09 14:14:40][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 55, in _run
    outputs = sorted(input_output_PerInput_dict[input],Artifact.name, reverse=False)
NameError: name 'Artifact' is not defined

[2018-Nov-09 14:14:48][Autoplacement_seq_plate_quant][CRITICAL] Encountered a AttributeError exception: type object 'str' has no attribute 'name'
[2018-Nov-09 14:14:48][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 55, in _run
    outputs = sorted(input_output_PerInput_dict[input],str.name, reverse=False)
AttributeError: type object 'str' has no attribute 'name'

[2018-Nov-09 14:17:41][Autoplacement_seq_plate_quant][CRITICAL] Encountered a AttributeError exception: 'Autoplacement_seq_plate_quant' object has no attribute 'name'
[2018-Nov-09 14:17:41][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 55, in _run
    outputs = sorted(input_output_PerInput_dict[input],self.name, reverse=False)
AttributeError: 'Autoplacement_seq_plate_quant' object has no attribute 'name'

[2018-Nov-09 14:20:28][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: One or more of the requested wells are already in use
[2018-Nov-09 14:20:28][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 107, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: One or more of the requested wells are already in use

