[2018-Nov-30 15:44:12][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 15:44:12][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 15:44:57][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'Artifact' object has no attribute 'loaction'
[2018-Nov-30 15:44:57][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 71, in _generate_csv_dict
    print(input_art.loaction[1],csv_line)
AttributeError: 'Artifact' object has no attribute 'loaction'

[2018-Nov-30 15:45:08][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 15:45:08][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 15:45:54][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict' object has no attribute 'sorted'
[2018-Nov-30 15:45:54][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 75, in _generate_csv_dict
    print(csv_dict.sorted())
AttributeError: 'dict' object has no attribute 'sorted'

[2018-Nov-30 15:46:10][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict' object has no attribute 'sort'
[2018-Nov-30 15:46:10][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 75, in _generate_csv_dict
    print(csv_dict.sort())
AttributeError: 'dict' object has no attribute 'sort'

[2018-Nov-30 15:47:47][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict_keys' object has no attribute 'sort'
[2018-Nov-30 15:47:47][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 76, in _generate_csv_dict
    keylist.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'

[2018-Nov-30 15:49:09][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a TypeError exception: unhashable type: 'dict_keys'
[2018-Nov-30 15:49:09][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 79, in _generate_csv_dict
    print(csv_dict[key])
TypeError: unhashable type: 'dict_keys'

[2018-Nov-30 15:50:27][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict_keys' object has no attribute 'sorted'
[2018-Nov-30 15:50:27][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 76, in _generate_csv_dict
    for key in csv_dict.keys().sorted():
AttributeError: 'dict_keys' object has no attribute 'sorted'

[2018-Nov-30 15:50:44][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a NameError exception: name 'sort' is not defined
[2018-Nov-30 15:50:44][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 76, in _generate_csv_dict
    for key in sort(csv_dict.keys()):
NameError: name 'sort' is not defined

[2018-Nov-30 15:51:07][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict_keys' object has no attribute 'sort'
[2018-Nov-30 15:51:07][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 76, in _generate_csv_dict
    for key in csv_dict.keys().sort():
AttributeError: 'dict_keys' object has no attribute 'sort'

[2018-Nov-30 15:51:34][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict_keys' object has no attribute 'sort'
[2018-Nov-30 15:51:34][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 78, in _generate_csv_dict
    for key in csv_dict.keys().sort():
AttributeError: 'dict_keys' object has no attribute 'sort'

[2018-Nov-30 15:51:59][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'dict_keys' object has no attribute 'sort'
[2018-Nov-30 15:51:59][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 78, in _generate_csv_dict
    for key in csv_dict.keys().sort():
AttributeError: 'dict_keys' object has no attribute 'sort'

[2018-Nov-30 15:53:41][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 15:53:41][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 15:54:02][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 15:54:02][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:05:20][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:05:20][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:10:19][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a AttributeError exception: 'Container' object has no attribute 'split'
[2018-Nov-30 16:10:19][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 67, in _generate_csv_dict
    if output.location[0].split("-")[1] == "IMP":
AttributeError: 'Container' object has no attribute 'split'

[2018-Nov-30 16:10:46][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:10:46][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:11:59][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:11:59][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:12:53][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:12:53][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:14:23][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:14:23][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:22:58][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-30 16:22:58][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 77, in _generate_csv_dict
    csv_line = [input_art.container.name, input_location, output_dict['IMP'][0], output_dict['IMP'][1],
IndexError: list index out of range

[2018-Nov-30 16:23:23][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-30 16:23:23][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 79, in _generate_csv_dict
    csv_line = [input_art.container.name, input_location, output_dict['IMP'][0], output_dict['IMP'][1],
IndexError: list index out of range

[2018-Nov-30 16:23:46][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a TypeError exception: append() takes exactly one argument (2 given)
[2018-Nov-30 16:23:46][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 70, in _generate_csv_dict
    output_dict['IMP'].append(output.location[0].name,output.location[1].replace(':', ''))
TypeError: append() takes exactly one argument (2 given)

[2018-Nov-30 16:24:03][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-30 16:24:03][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 294, in _run
    csv_array = self.generate_csv_array()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 262, in generate_csv_array
    csv_dict = self._generate_csv_dict()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\generate_hamilton_input_imp_ssqc.py", line 79, in _generate_csv_dict
    csv_line = [input_art.container.name, input_location, output_dict['IMP'][0], output_dict['IMP'][1],
IndexError: list index out of range

[2018-Nov-30 16:25:40][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:25:40][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:26:36][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'
[2018-Nov-30 16:26:36][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\mnt\\EGCGgeneral\\HAMILTON_INPUTS\\KAPA_CFP_TO_IMP_SSQC\\KAPA_CFP_TO_IMP_AND_SSQC.csv'

[2018-Nov-30 16:27:25][GenerateHamiltonInputIMPSSQC][CRITICAL] Encountered a FileNotFoundError exception: [Errno 2] No such file or directory: "C:\\Users\\dforth\\PycharmProjects\\clarity_scripts\\scripts\\''\\KAPA_CFP_TO_IMP_AND_SSQC.csv"
[2018-Nov-30 16:27:25][GenerateHamiltonInputIMPSSQC][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 136, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 298, in _run
    self.write_csv(self.shared_drive_file_path, csv_array)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 222, in write_csv
    with open(filename, 'w') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: "C:\\Users\\dforth\\PycharmProjects\\clarity_scripts\\scripts\\''\\KAPA_CFP_TO_IMP_AND_SSQC.csv"

