[2018-Oct-12 11:42:12][AutoplacementQPCR384][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-12 11:42:12][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 76, in _run
    output_placement_list.append((standards_dict[key],(output_container_list[0],plate_layout[well_counter])))
IndexError: list index out of range

[2018-Oct-12 11:42:40][AutoplacementQPCR384][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-12 11:42:40][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 77, in _run
    output_placement_list.append((standards_dict[key],(output_container_list[0],plate_layout[well_counter])))
IndexError: list index out of range

[2018-Oct-12 11:43:55][AutoplacementQPCR384][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-12 11:43:55][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 77, in _run
    output_placement_list.append((standards_dict[key],(output_container_list[0],plate_layout[well_counter])))
IndexError: list index out of range

[2018-Oct-12 11:44:18][AutoplacementQPCR384][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-12 11:44:18][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 78, in _run
    output_placement_list.append((standards_dict[key],(output_container_list[0],plate_layout[well_counter])))
IndexError: list index out of range

[2018-Oct-12 11:44:57][AutoplacementQPCR384][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-12 11:44:57][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 78, in _run
    output_placement_list.append((standards_dict[key],(output_container_list[0],plate_layout[well_counter])))
IndexError: list index out of range

