[2018-Nov-12 14:15:47][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:15:47][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 151, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:17:08][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:17:08][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 151, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:20:27][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:20:27][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 151, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:21:08][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:21:08][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 152, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:21:48][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:21:48][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 152, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:23:22][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:23:22][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 147, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:23:50][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:23:50][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 147, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:24:26][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:24:26][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 148, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:27:13][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:27:13][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 148, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:28:46][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:28:46][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 148, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:29:07][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:29:07][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 148, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:30:30][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]
[2018-Nov-12 14:30:30][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 149, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4, 27-4771-A:4]

[2018-Nov-12 14:42:09][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-C:4, 27-4771-C:4]
[2018-Nov-12 14:42:09][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 165, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-C:4, 27-4771-C:4]

[2018-Nov-12 14:43:29][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-C:4, 27-4771-C:4]
[2018-Nov-12 14:43:29][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 165, in _run
    self.process.step.set_placements(output_container_list, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate placements: [27-4771-A:4, 27-4771-A:4, 27-4771-C:4, 27-4771-C:4]

[2018-Nov-12 14:48:26][Autoplacement_seq_plate_quant][CRITICAL] Encountered a HTTPError exception: 404: Process not found: 24-31190
[2018-Nov-12 14:48:26][Autoplacement_seq_plate_quant][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_seq_plate_quant.py", line 20, in _run
    all_inputs = self.process.all_inputs(unique=True)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 474, in all_inputs
    ids = [io[0]['limsid'] for io in self.input_output_maps]
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 949, in __get__
    instance.get()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 86, in get
    self.root = self.lims.get(self.uri)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 96, in get
    return self.parse_response(r)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 404: Process not found: 24-31190

